package com.example.logintask.lib.utils

const val REQUEST_IMAGE_CAPTURE_PHOTO = 0x009
const val REQUEST_CODE_STORAGE_CAMERA_PERMISSION = 0x012
const val REQUEST_IMAGE_CAPTURE_FOR_DOCUMENT_PHOTO = 0x008

const val REQUEST_IMAGE_CAPTURE = 0x002

